#!/usr/bin/env ruby

$stdin.each_line do |line|
  # well skoglund made it sound like adding () around s would make read better
  # makes it return just a single s, if that!
  urls = line.scan(%r{http(s)?://\S+})
  urls.each do |url|
    puts url
  end
end
